name = "nanoworker"
version = "0.0.1"

description = "Lightweight JavaScript Workers for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "joshgillies", repo = "nanoworker" }
links = [{ title = "Website", href = "https://gleam.run" }]

gleam = "~> 1.0"

target = "javascript"

[javascript]
runtime = "deno"
typescript_declarations = true

[javascript.deno]
allow_read = ["gleam.toml", "test", "build"]
allow_write = ["build"]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_javascript = "~> 0.8"

[dev-dependencies]
gleeunit = "~> 1.0"
